export interface LootItem {
    id: string;
    icon: string;
    name: string;
    description: string;
}

export const LOOT_TABLE: LootItem[] = [
    {
        id: "excuse-certificate",
        icon: "📜",
        name: "EXCUSE CERTIFICATE",
        description: "Official proof that you were going to meditate yesterday.",
    },
    {
        id: "participation-trophy",
        icon: "🏆",
        name: "PARTICIPATION TROPHY",
        description: "You showed up. That's about it.",
    },
    {
        id: "doomscroll-receipt",
        icon: "🧾",
        name: "DOOMSCROLL RECEIPT",
        description: "47 minutes of scrolling, itemised. No refunds.",
    },
    {
        id: "healing-crystal",
        icon: "💎",
        name: "HEALING CRYSTAL",
        description: "Probably does something. Who knows.",
    },
    {
        id: "self-help-book",
        icon: "📚",
        name: "SELF-HELP BOOK",
        description: "Chapter 1 read. Chapter 2 pending since March.",
    },
    {
        id: "cold-brew",
        icon: "☕",
        name: "COLD BREW",
        description: "You meditated AND had coffee. Hero.",
    },
    {
        id: "granola-bar",
        icon: "🍫",
        name: "GRANOLA BAR",
        description: "Found in your meditation cushion. Still edible.",
    },
    {
        id: "scented-candle",
        icon: "🕯️",
        name: "SCENTED CANDLE",
        description: "Promises transformation. Delivers mild lavender.",
    },
    {
        id: "smartwatch",
        icon: "⌚",
        name: "SMARTWATCH",
        description: "Told you to breathe. You were already trying.",
    },
    {
        id: "phone",
        icon: "📱",
        name: "YOUR PHONE",
        description: "You know what you did.",
    },
    {
        id: "stray-thought",
        icon: "💭",
        name: "STRAY THOUGHT",
        description: "About an email. During your best moment.",
    },
    {
        id: "snooze-button",
        icon: "⏰",
        name: "SNOOZE BUTTON",
        description: "Hit five times before this session. A personal record.",
    },
    {
        id: "todo-list",
        icon: "📝",
        name: "TODO LIST",
        description: "Grew three items longer while you were sitting still.",
    },
    {
        id: "yoga-mat",
        icon: "🧘",
        name: "YOGA MAT",
        description: "Used as a rug since November.",
    },
    {
        id: "incense-stub",
        icon: "🌸",
        name: "INCENSE STUB",
        description: "Burned 40% before forgetting it existed.",
    },
    {
        id: "app-subscription",
        icon: "💸",
        name: "APP SUBSCRIPTION",
        description: "You have four of them. You use this one. Sometimes.",
    },
    {
        id: "notification",
        icon: "🔔",
        name: "NOTIFICATION",
        description: "From your other meditation app. Ironic.",
    },
    {
        id: "mindfulness-journal",
        icon: "📓",
        name: "MINDFULNESS JOURNAL",
        description: "Three entries. One is a grocery list.",
    },
    {
        id: "weighted-blanket",
        icon: "🛌",
        name: "WEIGHTED BLANKET",
        description: "You meditate better horizontal. This is fine.",
    },
    {
        id: "loose-change",
        icon: "🪙",
        name: "LOOSE CHANGE",
        description: "Found in the lining of your consciousness.",
    },

    // batch 2
    {
        id: "noise-cancelling-headphones",
        icon: "🎧",
        name: "NOISE-CANCELLING HEADPHONES",
        description: "For blocking out the world. Works on people too.",
    },
    {
        id: "neglected-succulent",
        icon: "🪴",
        name: "NEGLECTED SUCCULENT",
        description: "Survived six months of forgetting. Somehow.",
    },
    {
        id: "unfinished-podcast",
        icon: "🎙️",
        name: "UNFINISHED PODCAST",
        description: "Episode 3 of 8. Paused indefinitely.",
    },
    {
        id: "essential-oil",
        icon: "🧴",
        name: "ESSENTIAL OIL",
        description: "Eucalyptus. Allegedly does something.",
    },
    {
        id: "gym-membership",
        icon: "🏋️",
        name: "GYM MEMBERSHIP",
        description: "March was a great month.",
    },
    {
        id: "moon-phase-app",
        icon: "🌙",
        name: "MOON PHASE APP",
        description: "You paid £2.99 for this.",
    },
    {
        id: "do-not-disturb",
        icon: "📵",
        name: "DO NOT DISTURB",
        description: "Was on for three days. Nobody noticed.",
    },
    {
        id: "the-cat",
        icon: "🐈",
        name: "THE CAT",
        description: "Was not meditating. Was napping. Different.",
    },
    {
        id: "sleep-debt",
        icon: "💤",
        name: "SLEEP DEBT",
        description: "Compounding daily since 2019.",
    },
    {
        id: "vision-board",
        icon: "🎯",
        name: "VISION BOARD",
        description: "Made in January. It's May.",
    },
    {
        id: "avocado-toast",
        icon: "🥑",
        name: "AVOCADO TOAST",
        description: "Breakfast and a lifestyle simultaneously.",
    },
    {
        id: "intrusive-thought",
        icon: "🧠",
        name: "INTRUSIVE THOUGHT",
        description: "That thing you said in 2011. Still here.",
    },
    {
        id: "ceremonial-tea",
        icon: "🫖",
        name: "CEREMONIAL TEA",
        description: "Steeped too long. Very mindful.",
    },
    {
        id: "mirror-affirmation",
        icon: "🪞",
        name: "MIRROR AFFIRMATION",
        description: "You said it. You didn't fully mean it.",
    },
    {
        id: "bath-bomb",
        icon: "🛁",
        name: "BATH BOMB",
        description: "Promised clarity. Delivered glitter.",
    },

    // batch 3
    {
        id: "open-browser-tab",
        icon: "💻",
        name: "OPEN BROWSER TAB",
        description: "47 of them. This one is important.",
    },
    {
        id: "battery-anxiety",
        icon: "🔋",
        name: "BATTERY ANXIETY",
        description: "Phone at 12%. Session almost abandoned.",
    },
    {
        id: "unread-emails",
        icon: "📧",
        name: "UNREAD EMAILS",
        description: "1,847. You'll get to them.",
    },
    {
        id: "desktop-folder",
        icon: "🗂️",
        name: "DESKTOP FOLDER",
        description: "Called SORT THIS. Untouched since 2022.",
    },
    {
        id: "paused-video-game",
        icon: "🎮",
        name: "PAUSED VIDEO GAME",
        description: "Paused to meditate. Still paused. Probably fine.",
    },
    {
        id: "green-tea",
        icon: "🍵",
        name: "GREEN TEA",
        description: "Gone cold. Mindfully.",
    },
    {
        id: "green-juice",
        icon: "🧃",
        name: "GREEN JUICE",
        description: "Tastes like effort. Virtue purchased.",
    },
    {
        id: "stress-cookie",
        icon: "🍪",
        name: "STRESS COOKIE",
        description: "Technically post-session. Technically fine.",
    },
    {
        id: "impulse-purchase",
        icon: "🛍️",
        name: "IMPULSE PURCHASE",
        description: "Arrived Thursday. Already forgotten why.",
    },
    {
        id: "running-shoes",
        icon: "👟",
        name: "RUNNING SHOES",
        description: "Worn twice. Aspirationally placed by the door.",
    },
    {
        id: "laundry",
        icon: "🧺",
        name: "THE LAUNDRY",
        description: "It's been in there since the session before last.",
    },
    {
        id: "drafts-folder",
        icon: "🗑️",
        name: "DRAFTS FOLDER",
        description: "23 unsent texts. A museum of second thoughts.",
    },
    {
        id: "sticky-note",
        icon: "📌",
        name: "STICKY NOTE",
        description: "On the monitor since 2023. Now part of the monitor.",
    },
    {
        id: "fancy-pen",
        icon: "🖊️",
        name: "FANCY PEN",
        description: "Too nice to use. Used zero times.",
    },
    {
        id: "online-course",
        icon: "🏅",
        name: "ONLINE COURSE",
        description: "Module 2 of 9. Certificate pending since forever.",
    },
    {
        id: "houseplant-guilt",
        icon: "🌱",
        name: "HOUSEPLANT GUILT",
        description: "There are four of them. Two are fine.",
    },
    {
        id: "ambient-frustration",
        icon: "😤",
        name: "AMBIENT FRUSTRATION",
        description: "No specific cause. Just vibes.",
    },
    {
        id: "racing-thoughts",
        icon: "🌀",
        name: "RACING THOUGHTS",
        description: "Lapped you three times during the session.",
    },
    {
        id: "great-idea",
        icon: "💡",
        name: "GREAT IDEA",
        description: "Had it. Lost it. Gone forever.",
    },
    {
        id: "mala-beads",
        icon: "📿",
        name: "MALA BEADS",
        description: "Counted to 40. Lost track. Started over.",
    },
    {
        id: "singing-bowl",
        icon: "🎻",
        name: "SINGING BOWL",
        description: "Hit once. Sounded wrong. Never again.",
    },
    {
        id: "earworm",
        icon: "🎵",
        name: "EARWORM",
        description: "Hot cross buns. Entire session.",
    },
    {
        id: "peace",
        icon: "🕊️",
        name: "PEACE",
        description: "Glimpsed briefly. Gone when the phone buzzed.",
    },
    {
        id: "spare-key",
        icon: "🔑",
        name: "SPARE KEY",
        description: "Whose is this.",
    },
    {
        id: "heartbeat-check",
        icon: "🫀",
        name: "HEARTBEAT CHECK",
        description: "Noticed mid-session. Googled it after.",
    },

    // batch 4
    {
        id: "rain-sounds",
        icon: "🌧️",
        name: "RAIN SOUNDS",
        description: "The app ones. Actual rain didn't help.",
    },
    {
        id: "bird-that-interrupted",
        icon: "🐦",
        name: "BIRD THAT INTERRUPTED",
        description: "Landed outside. Whole session derailed.",
    },
    {
        id: "imagined-beach",
        icon: "🏖️",
        name: "IMAGINED BEACH",
        description: "Visualisation partially successful.",
    },
    {
        id: "ocean-sounds",
        icon: "🌊",
        name: "OCEAN SOUNDS",
        description: "Turned out to be the neighbour's playlist.",
    },
    {
        id: "rubber-duck",
        icon: "🦆",
        name: "RUBBER DUCK",
        description: "Debugging tool. Also emotional support.",
    },
    {
        id: "good-vibes",
        icon: "🌈",
        name: "GOOD VIBES",
        description: "Quantity: low. Still counting.",
    },
    {
        id: "life-hack",
        icon: "🪝",
        name: "LIFE HACK",
        description: "Read on reddit. Haven't tried. Probably works.",
    },
    {
        id: "unfinished-puzzle",
        icon: "🧩",
        name: "UNFINISHED PUZZLE",
        description: "Corner pieces only so far.",
    },
    {
        id: "refrigerator-magnet",
        icon: "🧲",
        name: "REFRIGERATOR MAGNET",
        description: "Says KEEP CALM. Noted.",
    },
    {
        id: "forgotten-reward-snack",
        icon: "🌮",
        name: "REWARD SNACK",
        description: "In the fridge. Earned. Will be consumed.",
    },
    {
        id: "disco-ball",
        icon: "🪩",
        name: "DISCO BALL",
        description: "Aspirational purchase. Still in the box.",
    },
    {
        id: "meditation-retreat-brochure",
        icon: "🏔️",
        name: "RETREAT BROCHURE",
        description: "Bookmarked. Flights never checked.",
    },
    {
        id: "zen-garden",
        icon: "🎑",
        name: "ZEN GARDEN",
        description: "Sand unraked. Rake lost. Very zen actually.",
    },
    {
        id: "sunrise-alarm",
        icon: "🌅",
        name: "SUNRISE ALARM",
        description: "Set once. Never again.",
    },
    {
        id: "herbal-supplement",
        icon: "🌿",
        name: "HERBAL SUPPLEMENT",
        description: "Directions: take mindfully.",
    },
    {
        id: "protein-shake",
        icon: "🥤",
        name: "PROTEIN SHAKE",
        description: "Residue in blender since Tuesday.",
    },
    {
        id: "overnight-oats",
        icon: "🫙",
        name: "OVERNIGHT OATS",
        description: "Prepared. Forgotten. Discovered.",
    },
    {
        id: "amazon-box",
        icon: "📦",
        name: "AMAZON BOX",
        description: "Fifth one this week. Something is happening.",
    },
    {
        id: "odd-sock",
        icon: "🧦",
        name: "ODD SOCK",
        description: "Pair not found. Peace made with it.",
    },
    {
        id: "spreadsheet",
        icon: "📊",
        name: "COLOUR-CODED SPREADSHEET",
        description: "So organised. Never opened again.",
    },
    {
        id: "blocked-calendar",
        icon: "🗓️",
        name: "BLOCKED CALENDAR",
        description: "Me time. Cancelled twice.",
    },
    {
        id: "meeting-notes",
        icon: "📋",
        name: "MEETING NOTES",
        description: "From Q2. Definitely still relevant.",
    },
    {
        id: "breathing-exercise",
        icon: "🫁",
        name: "BREATHING EXERCISE",
        description: "Inhale 4, hold 7, forget what comes next.",
    },
    {
        id: "crystal-ball",
        icon: "🔮",
        name: "CRYSTAL BALL",
        description: "Says try again later.",
    },
    {
        id: "massage-voucher",
        icon: "💆",
        name: "MASSAGE VOUCHER",
        description: "Expires this weekend. Has for three months.",
    },
    {
        id: "lotus-position-diagram",
        icon: "🪷",
        name: "LOTUS POSITION DIAGRAM",
        description: "Still can't do it.",
    },
    {
        id: "adaptogen",
        icon: "🧪",
        name: "ADAPTOGEN",
        description: "Allegedly reduces cortisol. Jury still out.",
    },
    {
        id: "mild-dissociation",
        icon: "🫠",
        name: "MILD DISSOCIATION",
        description: "Productive kind. Probably.",
    },
    {
        id: "white-flag",
        icon: "🏳️",
        name: "WHITE FLAG",
        description: "Not giving up. Just... pausing.",
    },
    {
        id: "good-intentions",
        icon: "🪄",
        name: "GOOD INTENTIONS",
        description: "Excellent quality. Limited durability.",
    },
    {
        id: "art-journal",
        icon: "🎨",
        name: "ART JOURNAL",
        description: "One page. It's a spiral.",
    },
    {
        id: "cushion-crumbs",
        icon: "🪑",
        name: "CUSHION CRUMBS",
        description: "Origin unknown. Presence accepted.",
    },
    {
        id: "unopened-gift",
        icon: "🎁",
        name: "UNOPENED GIFT",
        description: "From Christmas. It's fine where it is.",
    },
    {
        id: "tv-remote",
        icon: "📺",
        name: "TV REMOTE",
        description: "Lost under the cushion. Found during session.",
    },
    {
        id: "fly-in-the-room",
        icon: "🪟",
        name: "FLY IN THE ROOM",
        description: "Window was open. The fly is still there.",
    },
    {
        id: "paperclip",
        icon: "📎",
        name: "PAPERCLIP",
        description: "No paper. Just the clip.",
    },
    {
        id: "mechanical-keyboard",
        icon: "⌨️",
        name: "MECHANICAL KEYBOARD",
        description: "For focus. Very loud. Neighbours hate it.",
    },
    {
        id: "autumn-leaf",
        icon: "🍂",
        name: "AUTUMN LEAF",
        description: "Found in jacket pocket. No context.",
    },
    {
        id: "distraction-avoided",
        icon: "🪤",
        name: "DISTRACTION AVOIDED",
        description: "Eventually.",
    },
    {
        id: "calming-persona",
        icon: "🎭",
        name: "CALM PERSON PERSONA",
        description: "Works sometimes.",
    },
    {
        id: "snail-pace",
        icon: "🐌",
        name: "SNAIL'S PACE",
        description: "Achieved during session. Briefly.",
    },

    // batch 5 — food & drink
    {
        id: "third-coffee",
        icon: "☕",
        name: "THIRD COFFEE",
        description: "The one that fixes the second one.",
    },
    {
        id: "emergency-chocolate",
        icon: "🍫",
        name: "EMERGENCY CHOCOLATE",
        description: "Hidden from yourself. Found.",
    },
    {
        id: "bubble-tea",
        icon: "🧋",
        name: "BUBBLE TEA",
        description: "Ordered mindfully. Consumed mindlessly.",
    },
    {
        id: "cold-leftover-pizza",
        icon: "🍕",
        name: "COLD LEFTOVER PIZZA",
        description: "Eaten during session. No regrets.",
    },
    {
        id: "matcha-latte",
        icon: "🍵",
        name: "MATCHA LATTE",
        description: "£6. Tasted like lawn. Worth it.",
    },
    {
        id: "instant-noodles",
        icon: "🍜",
        name: "INSTANT NOODLES",
        description: "Post-session reward. No notes.",
    },
    {
        id: "stress-pretzel",
        icon: "🥨",
        name: "STRESS PRETZEL",
        description: "The shape mirrors your mind.",
    },
    {
        id: "forgotten-banana",
        icon: "🍌",
        name: "FORGOTTEN BANANA",
        description: "In the bag for four days. Still technically food.",
    },
    {
        id: "energy-drink",
        icon: "⚡",
        name: "ENERGY DRINK",
        description: "Immediately after the session. You earned it.",
    },
    {
        id: "oat-milk",
        icon: "🥛",
        name: "OAT MILK",
        description: "The ethical choice. Not the cheapest one.",
    },
    {
        id: "vitamin-d",
        icon: "🌞",
        name: "VITAMIN D SUPPLEMENT",
        description: "For the sun you are not getting.",
    },

    // batch 6 — tech & digital life
    {
        id: "ai-chatbot",
        icon: "🤖",
        name: "AI CHATBOT",
        description: "Asked for life advice. Got a bulleted list.",
    },
    {
        id: "forgotten-password",
        icon: "🔐",
        name: "FORGOTTEN PASSWORD",
        description: "14 attempts. Reset. Forgot again.",
    },
    {
        id: "weak-wifi",
        icon: "📡",
        name: "WEAK WIFI",
        description: "1 bar. During the most important part.",
    },
    {
        id: "loading-spinner",
        icon: "⏳",
        name: "LOADING SPINNER",
        description: "It's been a while.",
    },
    {
        id: "software-update",
        icon: "🔄",
        name: "SOFTWARE UPDATE",
        description: "Dismissed 17 times. Will recur.",
        },
    {
        id: "random-screenshot",
        icon: "📸",
        name: "MYSTERY SCREENSHOT",
        description: "Of what? No one knows.",
    },
    {
        id: "backup-drive",
        icon: "💾",
        name: "BACKUP DRIVE",
        description: "Hasn't been backed up since 2020.",
    },
    {
        id: "autocorrect",
        icon: "🔤",
        name: "AUTOCORRECT",
        description: "Changed 'peace' to 'peach.' Close enough.",
    },
    {
        id: "spam-email",
        icon: "🗳️",
        name: "SPAM EMAIL",
        description: "You've won something. You haven't.",
    },
    {
        id: "dark-mode",
        icon: "🌑",
        name: "DARK MODE",
        description: "On everything. Including your personality.",
    },
    {
        id: "404-page",
        icon: "🚧",
        name: "404 PAGE",
        description: "The thing you were looking for is not here either.",
    },

    // batch 7 — home & lifestyle
    {
        id: "couch-indent",
        icon: "🛋️",
        name: "COUCH INDENT",
        description: "Perfectly shaped. Scientifically yours.",
    },
    {
        id: "new-sponge",
        icon: "🧽",
        name: "NEW SPONGE",
        description: "Currently pristine. Give it a week.",
    },
    {
        id: "broom",
        icon: "🧹",
        name: "BROOM",
        description: "Bought for a productivity era. Swept once.",
    },
    {
        id: "bucket-list",
        icon: "🪣",
        name: "BUCKET LIST",
        description: "3 items. Added 2023. No progress.",
    },
    {
        id: "grocery-list-forgotten",
        icon: "🛒",
        name: "FORGOTTEN GROCERY LIST",
        description: "Left at home. Buying vibes instead.",
    },
    {
        id: "fifth-houseplant",
        icon: "🌵",
        name: "HOUSEPLANT NUMBER FIVE",
        description: "You said no more. You said that last time.",
    },
    {
        id: "hallway-ladder",
        icon: "🪜",
        name: "HALLWAY LADDER",
        description: "There since March. Shelf still unhung.",
    },
    {
        id: "aromatherapy-diffuser",
        icon: "🌬️",
        name: "AROMATHERAPY DIFFUSER",
        description: "Puffing lavender into the void.",
    },
    {
        id: "throw-pillow",
        icon: "🪆",
        name: "DECORATIVE PILLOW",
        description: "Cannot be slept on. Serves no function. Loved.",
    },
    {
        id: "miscellaneous-cables",
        icon: "🔌",
        name: "MYSTERY CABLE",
        description: "Fits nothing. Cannot be thrown away.",
    },
    {
        id: "half-burned-candle",
        icon: "🕯️",
        name: "HALF-BURNED CANDLE",
        description: "The good part already happened.",
    },

    // batch 8 — abstract & emotional
    {
        id: "the-quiet",
        icon: "😶",
        name: "THE QUIET",
        description: "Lasted 45 seconds. Precious.",
    },
    {
        id: "misplaced-ego",
        icon: "🫥",
        name: "MISPLACED EGO",
        description: "Temporarily lost during session. Back now.",
    },
    {
        id: "anxiety-rescheduled",
        icon: "🌪️",
        name: "RESCHEDULED ANXIETY",
        description: "Interrupted by session. Moved to 3pm.",
    },
    {
        id: "inner-critic-quiet",
        icon: "🤫",
        name: "INNER CRITIC (MUTED)",
        description: "Unusually quiet today. Suspicious.",
    },
    {
        id: "moment-of-pause",
        icon: "⏸️",
        name: "GENUINE PAUSE",
        description: "Achieved. For a moment. Real.",
    },
    {
        id: "lightness",
        icon: "🎈",
        name: "LIGHTNESS",
        description: "Unexpected. Brief. Real.",
    },
    {
        id: "recurring-thought",
        icon: "🔁",
        name: "RECURRING THOUGHT",
        description: "Fifth loop today. You know the one.",
    },
    {
        id: "brain-fog",
        icon: "🌫️",
        name: "BRAIN FOG",
        description: "Lifted 40% during session. Returned at the end.",
    },
    {
        id: "moment-of-clarity",
        icon: "💫",
        name: "MOMENT OF CLARITY",
        description: "0.3 seconds. Cherished.",
    },
    {
        id: "untapped-potential",
        icon: "🌟",
        name: "UNTAPPED POTENTIAL",
        description: "Abundant. Untapped.",
    },
    {
        id: "missing-piece",
        icon: "🧩",
        name: "MISSING PIECE",
        description: "Probably under the couch.",
    },
    {
        id: "big-picture",
        icon: "🔭",
        name: "THE BIG PICTURE",
        description: "Glimpsed. Promptly forgotten.",
    },

    // batch 9 — wellness & spiritual
    {
        id: "evil-eye-bracelet",
        icon: "🪬",
        name: "EVIL EYE BRACELET",
        description: "Protective. Stylish. Unverified.",
    },
    {
        id: "nazar",
        icon: "🧿",
        name: "NAZAR",
        description: "Protecting you from what exactly.",
    },
    {
        id: "saturn-retrograde",
        icon: "🪐",
        name: "SATURN IN RETROGRADE",
        description: "It's in retrograde. This explains everything.",
    },
    {
        id: "ancient-wisdom",
        icon: "🏺",
        name: "ANCIENT WISDOM",
        description: "From a book bought at an airport.",
    },
    {
        id: "moral-compass",
        icon: "🧭",
        name: "MORAL COMPASS",
        description: "Recalibrated. Slightly.",
    },
    {
        id: "lucky-clover",
        icon: "🍀",
        name: "LUCKY CLOVER",
        description: "Found. Digitally. Still counts.",
    },
    {
        id: "shooting-star",
        icon: "☄️",
        name: "SHOOTING STAR",
        description: "Wished on. Wish redacted.",
    },
    {
        id: "the-universe",
        icon: "🌌",
        name: "THE UNIVERSE",
        description: "Vast. Indifferent. Oddly comforting.",
    },
    {
        id: "global-perspective",
        icon: "🌐",
        name: "GLOBAL PERSPECTIVE",
        description: "Achieved. Lasted 2 minutes.",
    },
    {
        id: "self-compassion",
        icon: "🫶",
        name: "SELF-COMPASSION",
        description: "Located briefly. Lost again.",
    },
    {
        id: "guided-meditation-voice",
        icon: "🗣️",
        name: "GUIDED MEDITATION VOICE",
        description: "Too soothing. Fell asleep immediately.",
    },
    {
        id: "the-void",
        icon: "🕳️",
        name: "THE VOID",
        description: "Stared into it. It stared back. Nice.",
    },

    // batch 10 — miscellaneous
    {
        id: "rubber-band",
        icon: "🪢",
        name: "RUBBER BAND",
        description: "Around your wrist for a reason you can't recall.",
    },
    {
        id: "pen-with-no-lid",
        icon: "🖋️",
        name: "PEN WITH NO LID",
        description: "Still writes. Lid gone forever.",
    },
    {
        id: "parking-ticket",
        icon: "🎫",
        name: "PARKING TICKET",
        description: "From before you found inner peace.",
    },
    {
        id: "library-book",
        icon: "📖",
        name: "OVERDUE LIBRARY BOOK",
        description: "£4.20. Worth every penny of not finishing it.",
    },
    {
        id: "airport-novel",
        icon: "✈️",
        name: "AIRPORT NOVEL",
        description: "Chapter 6. You've been on that plane for two years.",
    },
    {
        id: "half-written-letter",
        icon: "✉️",
        name: "HALF-WRITTEN LETTER",
        description: "To no one specific. The thought was there.",
    },
    {
        id: "museum-ticket",
        icon: "🎟️",
        name: "MUSEUM TICKET STUB",
        description: "You went. You were cultural.",
    },
    {
        id: "world-record",
        icon: "📏",
        name: "UNOFFICIAL WORLD RECORD",
        description: "Most thoughts during a single breath. Unverified.",
    },
    {
        id: "certificate-of-breathing",
        icon: "🫧",
        name: "CERTIFICATE OF BREATHING",
        description: "You've been doing it your whole life. Impressive.",
    },
    {
        id: "motivational-poster",
        icon: "🖼️",
        name: "MOTIVATIONAL POSTER",
        description: "HANG IN THERE. The cat knows.",
    },
    {
        id: "loyalty-card",
        icon: "💳",
        name: "LOYALTY CARD",
        description: "7 stamps. 10 for a free one. Eternal.",
    },
    {
        id: "tide-pod",
        icon: "🧼",
        name: "LAUNDRY POD",
        description: "Found in the cushion. Do not eat.",
    },
    {
        id: "compass",
        icon: "🧭",
        name: "ACTUAL COMPASS",
        description: "Points north. Unhelpful for finding yourself.",
    },
    {
        id: "horoscope",
        icon: "♈",
        name: "TODAY'S HOROSCOPE",
        description: "Vague. Applicable. Believed anyway.",
    },
    {
        id: "expired-coupon",
        icon: "🏷️",
        name: "EXPIRED COUPON",
        description: "20% off. Was going to use it. Didn't.",
    },
];

/** Chance (0–1) that a session awards junk. Easy to tune. */
export const LOOT_DROP_CHANCE = 0.1;

/** Returns a random item, or null if the roll misses. */
export function rollLoot(): LootItem | null {
    if (Math.random() > LOOT_DROP_CHANCE) return null;
    return LOOT_TABLE[Math.floor(Math.random() * LOOT_TABLE.length)];
}
